apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: salt-master-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: salt-master
    spec:
      containers:
      - name: k8s-salt
        image: 601953533983.dkr.ecr.us-east-1.amazonaws.com/salt:latest
        volumeMounts:
          - mountPath: "/etc/salt/pki"
            name: salt-pki
          - mountPath: "/var/log/salt"
            name: salt-log
      volumes:
      - name: salt-pki
        persistentVolumeClaim:
          claimName: salt-pki-claim
      - name: salt-log
        persistentVolumeClaim:
          claimName: salt-log-claim
