kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pki-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi