kind: Pod
apiVersion: v1
metadata:
  name: salt-master-pod
spec:
  containers:
  - name: salt-master
    image: 601953533983.dkr.ecr.us-east-1.amazonaws.com/salt:latest
    volumeMounts:
      - name: efs-pvc
        mountPath: "/etc/salt/pki"
  restartPolicy: "Never"
  volumes:
    - name: efs-pvc
      persistentVolumeClaim:
        claimName: efs